version: '3.8'

services:
  sqlserver:
    image: mysql
    restart: unless-stopped
    container_name: sqlserver
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cardealerapp_qa
    ports:
      - "3307:3306"
    networks:
      - springboot-network

  springboot-app-qa:
    image: car-dealer-app
    container_name: car-dealer-app-qa
    depends_on:
      - sqlserver
    restart: on-failure
    build:
      context: .
    ports:
      - "8585:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sqlserver:3306/cardealerapp_qa?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILE_ACTIVE : qa
      SERVER_PORT: 8080
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
